manifest:
  defaults:
    revision: v0.3

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmkcommunity
      url-base: https://github.com

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: zmk-gpio-behavior
      remote: zmkcommunity
      revision: v0.1.0
      path: modules/zmk-gpio-behavior
      repo-path: zmkcommunity/zmk-gpio-behavior

  self:
    path: config
